#!/bin/bash
# 每日内容生成脚本 - 完全自动化

DATE=$(date +%Y-%m-%d)
CONTENT_DIR="~/claw-media/content"
WEBSITE_DIR="~/claw-media/website"

echo "=== Three Paws Media - Daily Content Generator ==="
echo "Date: $DATE"

# 1. 收集热点
echo "[1/4] Collecting trending topics..."
curl -s 'https://hn.algolia.com/api/v1/search?tags=front_page' > /tmp/hn_trends.json

# 2. 生成博客文章
echo "[2/4] Generating blog post..."
cat > "$WEBSITE_DIR/blog-$DATE.html" << EOF
<!DOCTYPE html>
<html>
<head>
    <title>Tech Digest - $DATE | Three Paws Media</title>
    <style>
        body { font-family: sans-serif; max-width: 700px; margin: 2rem auto; padding: 1rem; }
        h1 { border-bottom: 2px solid #333; padding-bottom: 0.5rem; }
        .post { margin: 2rem 0; }
        .meta { color: #666; font-size: 0.9rem; }
    </style>
</head>
<body>
    <h1>🐾 Tech Digest - $DATE</h1>
    <p class="meta">Generated by Three Paws AI</p>
    
    <div class="post">
        <h2>Today's Top Stories</h2>
        <p>Content auto-generated from Hacker News, GitHub, and tech sources.</p>
        <p>Full analysis coming soon...</p>
    </div>
    
    <footer>
        <p><a href="index.html">← Back to Home</a></p>
    </footer>
</body>
</html>
EOF

# 3. 更新网站索引
echo "[3/4] Updating site index..."
# 添加最新文章链接到首页

# 4. 部署到 GitHub Pages（如果配置了）
echo "[4/4] Deploying..."
cd "$WEBSITE_DIR"
git add .
git commit -m "Daily content update: $DATE"
# git push origin main

echo "=== Done! ==="
echo "Next: Configure Buttondown API for email distribution"
